version: "3"

services:
  web:
    build: web
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Websites configuration
      - ./web/vhosts:/etc/apache2/sites-enabled/:ro
      # Logs
      - ./web/logs:/var/log/apache2:rw,delegated
    depends_on:
      - mysql
#      - redis
      - solr
    tty: true

  mysql:
    build: mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    tty: true

#  redis:
#    build: redis
#    env_file: .env
#    ports:
#      - 6379:6379
#    volumes:
#      - redis:/data
#    tty: true

  maildev:
    image: djfarrelly/maildev
    env_file: .env
    depends_on:
      - web
    ports:
      - 1088:80
    tty: true

  solr:
    build: solr
    volumes:
      - ./solr/dist:/opt/solr/server/solr/solr5
    ports:
      - 8983:8983

volumes:
  mysql: {}
#  redis: {}
