version: "3"

services:
  web:
    build: web
    env_file: docker-env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/vhosts:/etc/apache2/sites-enabled/:ro
      - "~/www:/var/www/html:rw,delegated"
      - "~/logs/apache:/var/log/apache2:rw,delegated"
    tty: true

  mysql:
    build: mysql
    env_file: docker-env
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    tty: true

  redis:
    build: redis
    env_file: docker-env
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    tty: true

  maildev:
    image: djfarrelly/maildev
    env_file: docker-env
    depends_on:
      - web
    ports:
      - "1088:80"
    tty: true

volumes:
  mysql: {}
  redis: {}
